version: '3'

#services:
#  flea-market-was-01:
#    image: ghm8614/flea-market:latest
#    ports:
#      - "8081:8080"
#  flea-market-was-02:
#    image: ghm8614/flea-market:latest
#    ports:
#      - "8082:8080"