server:
  port: 8080

spring:
  config:
    import: optional:classpath:/secret-config-submodule/application-secret.yml

  profiles:
    include: secret

  datasource:
    hikari:
      master:
        driver-class-name: com.mysql.cj.jdbc.Driver
      slave:
        driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    cache:
      port: 6379
    session:
      port: 6379

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.ghm.giftcardfleamarket.domain.*.domain, com.ghm.giftcardfleamarket.domain.*.model