name: CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Make application-secret.yml
        run: |
          touch ./src/main/resources/application-secret.yml
          echo "${{ secrets.APPLICATION }}" > ./src/main/resources/application-secret.yml
          cat ./src/main/resources/application-secret.yml

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle (without Test)
        run: ./gradlew clean build -x test --stacktrace

        # 도커 로그인
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

        # 도커 이미지 빌드 및 푸쉬
      - name: Build Docker image & Push it to Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/flea-market:latest

        # 배포 및 백그라운드 실행
      - name: Deploy to NCP (WAS 01)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.NCP_SERVER_SSH_PUBLIC_IP }}
          port: ${{ secrets.NCP_SERVER_SSH_PORT_01 }}
          username: ${{ secrets.NCP_SERVER_USER }}
          password: ${{ secrets.NCP_SERVER_PASSWORD }}
          script: |
            cd /root/app/flea-market
            sudo docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_TOKEN }}
            sudo docker rm -f $(sudo docker ps -qa)
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/flea-market:latest
            sudo docker-compose up -d
            sudo docker image prune -f

      - name: Deploy to NCP (WAS 02)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.NCP_SERVER_SSH_PUBLIC_IP }}
          port: ${{ secrets.NCP_SERVER_SSH_PORT_02 }}
          username: ${{ secrets.NCP_SERVER_USER }}
          password: ${{ secrets.NCP_SERVER_PASSWORD }}
          script: |
            cd /root/app/flea-market
            sudo docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_TOKEN }}
            sudo docker rm -f $(sudo docker ps -qa)
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/fleamarket:latest
            sudo docker-compose up -d
            sudo docker image prune -f